version: '3.4'

services:
  account:
    build:
      # command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: sample
      DB_DATABASE: sample
      DB_PORT: 3306
      DB_HOST: db
      # BUNDLE_PATH: /bundle
      # - bundle:/bundle
    ports:
      - '8080:8080'
#    depends_on:
#      - db
    expose:
      - '3000'
    entrypoint: sh ./entrypoints/account.sh
