CREATE DATABASE mohamedsayed;
use exampleDB;

CREATE TABLE public."Accounts"
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    password character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default" unique,
    username character varying(255) COLLATE pg_catalog."default",
    profile_photo character varying(255) COLLATE pg_catalog."default",
    number_of_followers integer,
    type character varying(255) COLLATE pg_catalog."default"
);

CREATE TABLE public."Users"
(
    id int PRIMARY KEY ,
    is_premium boolean,
    bit_rate integer,
    CONSTRAINT "Users_user_id_fkey" FOREIGN KEY (id)
        REFERENCES public."Accounts" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE public."Artists"
(
    id int PRIMARY KEY,
    rating double precision,
    number_of_ratings integer default 0,
       CONSTRAINT "Users_user_id_fkey" FOREIGN KEY (id)
        REFERENCES public."Accounts" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE public."Reports"
(
id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	reason text COLLATE pg_catalog."default",
    reported_id integer,
    user_id integer,
    CONSTRAINT "Reports_reported_id_fkey" FOREIGN KEY (reported_id)
        REFERENCES public."Accounts" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT "Reports_user_id_fkey" FOREIGN KEY (user_id)
        REFERENCES public."Accounts" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE public."Ads"
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_url character varying(255) COLLATE pg_catalog."default",
    ad_photo_url character varying(255) COLLATE pg_catalog."default"
);

CREATE  TABLE public."Albums"
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY not null,
    name character varying(255) COLLATE pg_catalog."default" not null,
    genre character varying(255) COLLATE pg_catalog."default" not null,
    cover_photo character varying(255) COLLATE pg_catalog."default" not null,
    rating double precision DEFAULT 0,
    artist_id integer not null,
    number_of_ratings integer default 0,
    CONSTRAINT "Albums_artist_id_fkey" FOREIGN KEY (artist_id)
        REFERENCES public."Accounts" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE public."Songs"
(
   id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) COLLATE pg_catalog."default" not null,
    genre character varying(255) COLLATE pg_catalog."default" not null,
    rating double precision default 0,
    song_url character varying(255) COLLATE pg_catalog."default" not null,
    total_streams integer default 0,
    release_date date,
    artist_id integer not null,
    album_id integer not null,
    number_of_ratings integer default 0,
    CONSTRAINT "Songs_album_id_fkey" FOREIGN KEY (album_id)
        REFERENCES public."Albums" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT "Songs_artist_id_fkey" FOREIGN KEY (artist_id)
        REFERENCES public."Accounts" (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
